package esmukanov.evote_system.audit.enums;

public enum AuditAction {
    USER_REGISTERED,
    USER_LOGIN_SUCCESS,
    USER_LOGIN_FAILED,
    USER_LOGOUT,
    TOKEN_REFRESHED,

    USER_CREATED,
    USER_UPDATED,
    USER_STATUS_CHANGED,
    USER_ROLES_CHANGED,
    USER_DELETED,

    ELECTION_CREATED,
    ELECTION_UPDATED,
    ELECTION_PUBLISHED,
    ELECTION_STARTED,
    ELECTION_COMPLETED,

    ELECTION_OPTION_CREATED,
    ELECTION_OPTION_UPDATED,
    ELECTION_OPTION_DELETED,

    VOTE_CAST,
    VOTE_REJECTED_ALREADY_VOTED,
    VOTE_REJECTED_ELECTION_NOT_ACTIVE,
    VOTE_REJECTED_ACCESS_DENIED,

    RESULT_CALCULATED,
    RESULT_PUBLISHED,
    RESULT_ACCESS_DENIED,

    BLOCKCHAIN_RECORD_CREATED,
    BLOCKCHAIN_RECORD_VERIFIED,
    BLOCKCHAIN_VERIFICATION_FAILED
}
