version: "3.9"

services:
  database:
    image: postgres:17
    container_name: evote-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: evote_system
      POSTGRES_USER: evote
      POSTGRES_PASSWORD: evote_pass
    ports:
      - "5001:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: