server:
  port: 9999

spring:
  application:
    name: Evote System
  profiles:
    include: datasource

app:
  jobs:
    election-active: PT1M
    election-finish: PT5M
  security:
    vote-salt: "change-me-vote-secret-salt"
    jwt:
      secret: QUBLEW52sg3ftVkbcZl7SkfdpnHLjyrIYSInf1dU4c8=
      access-token-ttl: 1h
      refresh-token-ttl: 30d